[book]
title = "Java Bytecode Optimization and Virtual Machine Runtimes"
authors = ["Luis Landgrave", "Microsoft Copilot"]
description = "Talk about Java Bytecode Optimization and Virtual Machine Runtimes"

[rust]
edition = "2024"

[build]
build-dir = "build"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
#additional-css = ["custom.css"]

[output.html.search]
#limit-results = 15